# As this application identifies the Eureka Service,
# we have to prevent it from registering to itself
# as a client.
spring:
  application:
    name: eureka-service
    
server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
  server:
    wait-time-in-ms-when-sync-empty: 0
    eviction-interval-timer-in-ms: 10000